#include<iostream>
#include<conio.h>
#include<windows.h>
#include<process.h>

using namespace std;


int main()
{
	//PRINT CODE//
	cout<<"NATIONAL UNIVERSITY";
	cout<<"\nManila";
	
	cout<<"\n\nCOLLEGE OF ENGINEERING";
	cout<<"\nComputer Engineering Department";
	
	cout<<"\n\n        CPPROG2L-COE211";
	cout<<"\n        Program Logic and Design";
	
	cout<<"\n\nSETH MARCUS S. MARTIN";
	
	cout<<"\n\n        ENGR.MARLON G. BAGARA";
	cout<<"\n        Professor";
}
